# Generated by Django 3.0.3 on 2021-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.FloatField()),
                ('salary_per_hour', models.FloatField()),
                ('total_salary', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('due', 'due')], max_length=6)),
            ],
        ),
    ]
